require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'invision_app_rn' do
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  # add pods for any other desired Firebase products
  #. https://firebase.google.com/docs/ios/setup#available-pods
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])





  target 'invision_app_rnTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'invision_app_rn-tvOS' do
  # Pods for invision_app_rn-tvOS

  target 'invision_app_rn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
